In [2]:
import numpy as np
import pandas as pd
data  = pd.read_csv(r"iris.arff.csv",header =0)
# data.head(10)  头十
# data.tail()  尾5
# data.sample() 随机抽。默认1，可调
data["class"]= data["class"].map({"Iris-virginica":0,"Iris-setosa":1,"Iris-versicolor":2} )
# data.drop("Id",axis=1,inplace=True)
data.drop_duplicates(inplace=True)
data["class"].value_counts()

2    50
0    49
1    48
Name: class, dtype: int64

In [5]:
class KNN:
    '''使用python实现K近邻（分类）'''
    def _init_(self,k):
        '''初始化方法'''
        
    def fit(self,X,y):
        '''训练方法
        
        
    X:类数组类型，形状为:[样本数量，特征数量]
      待训练的样本特征（属性）
    
    
    y:类数组类型，形状为：【样本数量】
    每个样本的目标值（标签）'''
    self.X = np.asarray(X)
    self.y = np.asarray(y)
   
    def predict(self,X:
    ''' X:类数组类型，形状为:[样本数量，特征数量]
      待训练的样本特征（属性）'''
    
    X = np.asarray(X)
    result = []
    for x in  X:
        #对于测试集中的每一个样本，依次与训练集中所有样本求距离
        dis = np.sqrt(np.sum((x - self.X)**2,axis = 1))
        #返回数组排序后，每个元素在原数组中的索引
        index = dis.argsort()
        #进行截断，只取前K个数，【去距离最近的k个元素索引】
        index = index[:self.k]
        #返回数组中每个元素出现的次数，元素必须是非负的整数
        count = np.bincount(self.y[index])
        #返回ndarray数组中，值最大的元素对应的索引，该索引就是我们判定的类别
        #最大元素索引，就是出现次数最多的元素
        result.append(count.argmax())
    return np.asarray(result)


SyntaxError: invalid syntax (TEMPFI~1/ipykernel_11984/3155593462.py, line 23)

In [4]:
#提取出每个类别的鸢尾花数据
t1 = data[data[class] == 0]
t2 = data[data[class] == 1]
t3 = data[data[class] == 2]
#对每个类别数据进行洗牌
t0 = t0.sample(len(t0),random_state =0 )
t1 = t1.sample(len(t1),random_state =0)
t2 = t2.sample(len(t2),random_state =0)
train_X = pd.concat([t0.iloc[:40,:-1],t1.iloc[:40,:-1],t2.iloc[:40,:-1]],axis=0)
train_y = pd.concat([t0.iloc[:40,-1],t1.iloc[:40,-1],t2.iloc[:40,-1]],axis=0)
test_X = pd.concat([t0.iloc[40:,:-1],t1.iloc[40:,:-1],t2.iloc[40:,:-1]],axis=0)
test_y = pd.concat([t0.iloc[40:,-1],t1.iloc[40:,-1],t2.iloc[40:,-1]],axis=0)
#创建KNN对象，进行训练和测试
knn = KNN(k=3)
#进行训练
knn.fit(train_X,train_y)
#进行测试，获得测试结果
result = knn.predict(test_X)
display(result)
display(test_y)

SyntaxError: invalid syntax (TEMPFI~1/ipykernel_11984/3603646398.py, line 2)

In [3]:
a = np.array([[[1,2,3,2],[1,2,3,1],[2,3,4,1]],[[1,0,2,0],[2,1,2,0],[2,1,1,1]]])


In [4]:
a

array([[[1, 2, 3, 2],
        [1, 2, 3, 1],
        [2, 3, 4, 1]],

       [[1, 0, 2, 0],
        [2, 1, 2, 0],
        [2, 1, 1, 1]]])

In [5]:
a.sum(axis=0)

array([[2, 2, 5, 2],
       [3, 3, 5, 1],
       [4, 4, 5, 2]])

In [6]:
a.sum(axis=1)

array([[ 4,  7, 10,  4],
       [ 5,  2,  5,  1]])

In [7]:
a.sum(axis=2)

array([[ 8,  7, 10],
       [ 3,  5,  5]])